//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t APP_SystemClockConfig(int32_t a1, int32_t a2);
int32_t Bootloader_Init(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t Bootloader_ProtocolDetection(void);
int32_t BSP_PB_GetState(int32_t a1);
int32_t BSP_PB_Init(int32_t a1, int32_t a2);
int32_t ExtendedErase(void);
int32_t GetAddressArea(int32_t * a1);
int32_t Go(void);
int32_t JumpToAddress(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t LL_SetSystemCoreClock(int32_t result);
int32_t MassErase(void);
int32_t PageErase(int32_t a1, uint32_t a2, uint32_t a3);
int32_t ReadMemory(void);
int32_t SectorErase(int32_t a1, uint32_t a2, int32_t a3, int32_t a4);
int32_t USART_ReadByte(void);
int32_t USART_SendByte(int32_t result);
int32_t WDG_Init(void);
int32_t WDG_Refresh(void);
int32_t WriteFlash(int32_t a1, int32_t a2, int32_t a3);
int32_t WriteMemory(void);
int32_t WriteOption(int32_t a1, int32_t a2, uint32_t a3, int32_t a4);
int32_t WriteProtect(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0x7a1200; // 0x20000000
int32_t g2 = 0x50000000; // 0x20000004
int16_t * g3 = NULL; // 0x20000024
char g4 = 0; // 0x20000025
char g5 = 0; // 0x20000026
char g6 = 0; // 0x20000027
int32_t g7 = 0; // 0x20000028
int32_t g8 = -0x3000001; // 0x8001000
char * g9 = "\x01\x02\x11!1Dcs\x82\x92\x03\x35\x01"; // 0x800110d
int32_t g10 = 0x8000135; // 0x8001118
int32_t g11;

// ------------------------ Functions -------------------------

// Address range: 0x80001f0 - 0x800022a
int main(int argc, char ** argv) {
    // 0x80001f0
    BSP_PB_Init(0, 0);
    int32_t v1; // 0x80001f0
    if (BSP_PB_GetState(0) == 0) {
        // 0x8000222
        JumpToAddress(&g8, 0, v1, v1);
    }
    uint32_t v2 = *(int32_t *)0x1fff0f10; // 0x8000208
    Bootloader_Init(APP_SystemClockConfig(v2 % 0x2000 | 0x8000, 0x16e3600), 0x16e3600, v1, 0x8000);
    while (true) {
        // 0x800021c
        Bootloader_ProtocolDetection();
    }
}

// Address range: 0x8000238 - 0x80003d2
int32_t Bootloader_Init(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x8000238
    WDG_Init();
    *(int32_t *)0x40021034 = *(int32_t *)0x40021034 | 1;
    *(int32_t *)0x50000000 = *(int32_t *)0x50000000 & 0x3fcfff3f;
    int32_t v1 = *(int32_t *)0x1fff0d90; // 0x8000260
    if ((v1 & 8) == 0) {
        // 0x8000266
        *(int32_t *)0x5000000c = *(int32_t *)0x5000000c | 64;
    }
    if ((v1 & 1024) == 0) {
        // 0x8000272
        *(int32_t *)0x5000000c = *(int32_t *)0x5000000c | 0x100000;
    }
    if ((v1 & 0x8000) == 0) {
        // 0x8000284
        *(int32_t *)0x5000000c = *(int32_t *)0x5000000c | 0x40000000;
    }
    int32_t v2 = *(int32_t *)0x50000010;
    WDG_Refresh();
    int32_t v3 = v2;
    int32_t v4 = v2 & 8; // 0x80002be
    int32_t v5 = v2 & 0x8000;
    int32_t v6 = v2 & 1024;
    int32_t v7 = v3 & 1024;
    while (v7 == 0 != v6 != 0) {
        int32_t v8 = v5;
        v5 = v3 & 0x8000;
        if (v8 != 0 == v5 == 0) {
            // 0x80002ea
            *(int32_t *)0x50000000 = -0x54000001;
            *(int32_t *)0x50000024 = *(int32_t *)0x50000024 | 0x11000000;
            goto lab_0x8000304;
        }
        int32_t v9 = v4;
        v3 = *(int32_t *)0x50000010;
        v4 = v3 & 8;
        WDG_Refresh();
        if (v4 == 0 == (v9 != 0)) {
            // 0x800038c
            *(int32_t *)0x50000000 = -0x14000051;
            *(int32_t *)0x50000020 = *(int32_t *)0x50000020 | 0x1100;
            goto lab_0x8000304;
        }
        v6 = v7;
        v7 = v3 & 1024;
    }
    // 0x80003a4
    *(int32_t *)0x50000000 = -0x14140001;
    *(int32_t *)0x50000024 = *(int32_t *)0x50000024 | 272;
    goto lab_0x8000304;
  lab_0x8000304:
    // 0x8000304
    *(int32_t *)0x40021040 = *(int32_t *)0x40021040 | 0x4000;
    *(int32_t *)0x4001380c = *(int32_t *)0x4001380c | 0x1400;
    *(int32_t *)0x40013808 = 208;
    *(int32_t *)0x40013814 = *(int32_t *)0x40013814 & -0x7001 | 0x1000;
    *(int32_t *)0x4001380c = *(int32_t *)0x4001380c | 0x2000;
    int32_t v10 = *(int32_t *)0x40013800; // 0x800033c
    while ((v10 & 1024) == 0) {
        // continue -> 0x800033c
    }
    if ((v10 & 2048) == 0) {
        uint32_t v11 = *(int32_t *)0x40013808; // 0x8000348
        if (v11 >= 0x553a != v11 != 0x553a) {
            if (v11 != 23 && v11 >= 23) {
                // 0x8000356
                __asm_cpsid();
                *(int32_t *)0x40013800 = *(int32_t *)0x40013800 | 0x1000;
                *(int32_t *)0x40013814 = *(int32_t *)0x40013814 & -0x1001;
                *(int32_t *)0x40013800 = *(int32_t *)0x40013800 & -97;
                *(int32_t *)0x4001380c = *(int32_t *)0x4001380c | 12;
                return USART_SendByte(121);
            }
        }
    }
    // 0x80003c0
    __asm_dsb();
    *(int32_t *)-0x1fff12f4 = 0x5fa0004;
    __asm_dsb();
    while (true) {
        // continue -> 0x80003ce
    }
}

// Address range: 0x8000404 - 0x80004f2
int32_t GetAddressArea(int32_t * a1) {
    int32_t v1 = USART_ReadByte(); // 0x8000408
    *(char *)&g3 = (char)v1;
    g4 = USART_ReadByte();
    g5 = USART_ReadByte();
    g6 = USART_ReadByte();
    int32_t v2 = USART_ReadByte(); // 0x8000422
    int32_t v3 = 0; // 0x800042a
    int32_t v4 = (int32_t)&g3;
    int32_t v5 = v4 + 1; // 0x800042e
    v3 ^= (int32_t)*(char *)v4;
    while (v5 != (int32_t)&g7) {
        // 0x800042c
        v4 = v5;
        v5 = v4 + 1;
        v3 ^= (int32_t)*(char *)v4;
    }
    if (v2 != v3) {
        // 0x800043c
        return 0;
    }
    // 0x800043e
    USART_SendByte(121);
    unsigned char v6 = *(char *)&g3; // 0x8000444
    uint32_t v7 = 0x10000 * (int32_t)g4 | 0x1000000 * (int32_t)v6 | 256 * (int32_t)g5 | (int32_t)g6; // 0x8000456
    *a1 = v7;
    if (v7 == 0x1ffff7e8) {
        // 0x80004a6
        *a1 = 0x1fff0e00;
        // 0x800043c
        return 3;
    }
    if (v7 > 0x1ffff7e8) {
        if (v7 == 0x1ffff800) {
            // 0x8000486
            *a1 = 0x1fff0e80;
            // 0x800043c
            return 3;
        }
    } else {
        // 0x8000462
        switch (v7) {
            case 0x1ffff7e0: {
            }
            case 0x1ffff7cc: {
                // 0x800043c
                return 3;
            }
            case 0x1ffff7a6: {
                // 0x8000474
                *a1 = 0x8000bfc;
                // 0x800043c
                return 1;
            }
        }
        if (v7 < 0x8000000) {
            // 0x800043c
            return 0;
        }
        // 0x80004ac
        if (v7 < 0x800a000) {
            // 0x800043c
            return 1;
        }
    }
    if (v7 != 0x200001ff && v7 >= 0x200001ff) {
        // 0x80004d2
        if (v7 < 0x20002000) {
            // 0x800043c
            return 2;
        }
        // 0x800043c
        return 0;
    }
    if (v7 == 0x1ffeffff || v7 < 0x1ffeffff) {
        // 0x800043c
        return 0;
    }
    // 0x80004e0
    if (v7 == 0x1fff0dff || v7 < 0x1fff0dff) {
        // 0x800043c
        return 5;
    }
    // 0x80004e8
    if (v7 == 0x1fff0fff || v7 < 0x1fff0fff) {
        // 0x800043c
        return 3;
    }
    // 0x800043c
    return 0;
}

// Address range: 0x8000534 - 0x80005f4
int32_t ReadMemory(void) {
    // 0x8000534
    int32_t v1; // bp-28, 0x8000534
    int32_t v2 = GetAddressArea(&v1); // 0x800053a
    if (v2 == 0) {
        // 0x8000544
        return 0;
    }
    int32_t v3 = USART_ReadByte(); // 0x8000548
    *(char *)&g3 = (char)v3;
    if ((USART_ReadByte() ^ v3) % 256 != 255) {
        // 0x8000544
        return 0;
    }
    // 0x800055e
    USART_SendByte(121);
    switch (v1) {
        case 0x1ffff7e0: {
        }
        case 0x1ffff7cc: {
            // 0x8000594
            g4 = 40;
            g5 = 0;
            *(char *)&g7 = 0;
            g6 = 8;
            USART_SendByte(40);
            if (*(char *)&g3 == 0) {
                // 0x8000544
                return 1;
            }
            uint32_t v4 = 1; // 0x80005c8
            unsigned char v5 = *(char *)(v4 + (int32_t)&g3 + 1); // 0x80005ba
            USART_SendByte((int32_t)v5);
            v4 = (v4 + 1) % 0x10000;
            while (v4 <= (int32_t)*(char *)&g3) {
                // 0x80005b8
                v5 = *(char *)(v4 + (int32_t)&g3 + 1);
                USART_SendByte((int32_t)v5);
                v4 = (v4 + 1) % 0x10000;
            }
            // 0x8000544
            return 1;
        }
    }
    if (v2 == 1) {
        int32_t v6 = 0; // 0x80005d6
        if (*(int32_t *)0x40022020 % 256 != 170) {
            USART_SendByte((int32_t)*(char *)v6);
            uint32_t v7 = (v6 + 1) % 0x10000; // 0x80005e8
            v6 = v7;
            while (v7 <= (int32_t)*(char *)&g3) {
                // 0x80005dc
                USART_SendByte((int32_t)*(char *)v6);
                v7 = (v6 + 1) % 0x10000;
                v6 = v7;
            }
            // 0x8000544
            return 1;
        }
    }
    // 0x800057c
    USART_SendByte((int32_t)*(char *)v1);
    if (*(char *)&g3 == 0) {
        // 0x8000544
        return 1;
    }
    uint32_t v8 = 1; // 0x800058e
    USART_SendByte((int32_t)*(char *)(v1 + v8));
    v8 = (v8 + 1) % 0x10000;
    while (v8 <= (int32_t)*(char *)&g3) {
        // 0x800057a
        USART_SendByte((int32_t)*(char *)(v1 + v8));
        v8 = (v8 + 1) % 0x10000;
    }
    // 0x8000544
    return 1;
}

// Address range: 0x8000608 - 0x800062a
int32_t JumpToAddress(int32_t * a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t result = (int32_t)a1;
    if ((result & 0x2ffe0000) == 0x20000000) {
        // 0x800061a
        return __asm_cpsie(result, a2, 0x20000000, 0x20000000);
    }
    // 0x8000626
    return result;
}

// Address range: 0x8000630 - 0x80006c0
int32_t WriteMemory(void) {
    // 0x8000630
    int32_t v1; // bp-28, 0x8000630
    int32_t v2 = GetAddressArea(&v1); // 0x800063a
    uint32_t v3 = (v2 + 255) % 256; // 0x8000642
    if (v3 != 2 && v3 >= 2) {
        // 0x800064c
        return 0;
    }
    int32_t v4 = USART_ReadByte(); // 0x8000654
    int32_t v5 = 0;
    int32_t v6 = USART_ReadByte(); // 0x8000660
    int32_t v7 = (v5 + 1) % 0x10000; // 0x8000666
    *(char *)(v5 + (int32_t)&g3) = (char)v6;
    while (v7 <= v4) {
        // 0x8000660
        v5 = v7;
        v6 = USART_ReadByte();
        v7 = (v5 + 1) % 0x10000;
        *(char *)(v5 + (int32_t)&g3) = (char)v6;
    }
    int32_t v8 = USART_ReadByte(); // 0x8000670
    int32_t v9 = v4; // 0x800067a
    int32_t v10 = (int32_t)&g3;
    int32_t v11 = v10 + 1; // 0x800067e
    v9 = v9 % 256 ^ (int32_t)*(char *)v10;
    while (v11 != v4 + (int32_t)&g4) {
        // 0x800067c
        v10 = v11;
        v11 = v10 + 1;
        v9 = v9 % 256 ^ (int32_t)*(char *)v10;
    }
    // 0x8000688
    if (v8 != v9) {
        // 0x800064c
        return 0;
    }
    // 0x800068c
    if (v2 != 2) {
        // 0x8000692
        int32_t result; // 0x8000630
        if (v2 == 3) {
            // 0x80006a2
            result = WriteOption(v1, (int32_t)&g3, v4, 3);
        } else {
            // 0x800069c
            result = WriteFlash(v1, (int32_t)&g3, v4);
        }
        // 0x800064c
        return result;
    }
    int32_t v12 = 0;
    char v13 = *(char *)(int32_t)&g3; // 0x80006ae
    int32_t v14 = v12 + 1; // 0x80006b2
    *(char *)(v1 + v12) = v13;
    int32_t v15 = v14 % 0x10000; // 0x80006b6
    while (v15 <= v4) {
        // 0x80006ac
        v12 = v14;
        v13 = *(char *)(v15 + (int32_t)&g3);
        v14 = v12 + 1;
        *(char *)(v1 + v12) = v13;
        v15 = v14 % 0x10000;
    }
    // 0x800064c
    return 1;
}

// Address range: 0x80006c4 - 0x8000772
int32_t ExtendedErase(void) {
    int32_t v1 = USART_ReadByte(); // 0x80006ce
    uint32_t v2 = USART_ReadByte(); // 0x80006d4
    int32_t v3 = (v2 ^ v1) % 256; // 0x80006dc
    int32_t result; // 0x80006c4
    if (v1 == 255) {
        // 0x8000758
        result = 0;
        if (USART_ReadByte() == v3) {
            // 0x8000760
            result = MassErase();
        }
        // 0x8000724
        return result;
    }
    int32_t v4 = 2 * v2; // 0x80006ec
    int32_t v5 = 0;
    int32_t v6 = USART_ReadByte(); // 0x80006f2
    uint32_t v7 = (v5 + 1) % 256; // 0x80006f8
    *(char *)(v5 + (int32_t)&g3) = (char)v6;
    while (v7 < v4 + 2) {
        // 0x80006f2
        v5 = v7;
        v6 = USART_ReadByte();
        v7 = (v5 + 1) % 256;
        *(char *)(v5 + (int32_t)&g3) = (char)v6;
    }
    int32_t v8 = (int32_t)&g3; // 0x800070a
    int32_t v9 = v4 & 0xfffe | 1; // 0x800070a
    int32_t v10 = v3; // 0x800070a
    v9 = (v9 + 0xffff) % 0x10000;
    v10 ^= (int32_t)*(char *)v8;
    v8++;
    while (v9 != 0xffff) {
        // 0x800070c
        v9 = (v9 + 0xffff) % 0x10000;
        v10 ^= (int32_t)*(char *)v8;
        v8++;
    }
    // 0x800071a
    if (USART_ReadByte() != v10) {
        // 0x8000724
        return 0;
    }
    uint32_t v11 = 0; // 0x8000720
    int32_t v12 = 2 * v11; // 0x8000730
    char * v13 = (char *)(v12 + (int32_t)&g3); // 0x8000734
    char * v14 = (char *)((v12 | 1) + (int32_t)&g3); // 0x8000736
    v11 = (v11 + 1) % 256;
    *v13 = *v14;
    *v14 = *v13;
    while (v2 >= v11) {
        // 0x8000730
        v12 = 2 * v11;
        v13 = (char *)(v12 + (int32_t)&g3);
        v14 = (char *)((v12 | 1) + (int32_t)&g3);
        v11 = (v11 + 1) % 256;
        *v13 = *v14;
        *v14 = *v13;
    }
    // 0x8000744
    result = 0;
    switch (v1) {
        case 0: {
            // 0x8000766
            result = PageErase((int32_t)&g3, v3, 8);
            // break -> 0x8000724
            break;
        }
        case 32: {
            // 0x800074e
            result = SectorErase((int32_t)&g3, v2, v12, 32);
            // break -> 0x8000724
            break;
        }
    }
    // 0x8000724
    return result;
}

// Address range: 0x800077c - 0x80007ee
int32_t WriteProtect(void) {
    int32_t v1 = USART_ReadByte(); // 0x8000782
    int32_t v2 = 0;
    int32_t v3 = USART_ReadByte(); // 0x8000792
    int32_t v4 = (v2 + 1) % 0x10000; // 0x800079a
    *(char *)(v2 + (int32_t)&g3) = (char)v3;
    while (v4 <= v1) {
        // 0x8000792
        v2 = v4;
        v3 = USART_ReadByte();
        v4 = (v2 + 1) % 0x10000;
        *(char *)(v2 + (int32_t)&g3) = (char)v3;
    }
    int32_t v5 = USART_ReadByte(); // 0x80007a4
    int32_t v6 = v1; // 0x80007ae
    int32_t v7 = (int32_t)&g3;
    int32_t v8 = v7 + 1; // 0x80007b2
    v6 = v6 % 256 ^ (int32_t)*(char *)v7;
    while (v1 + (int32_t)&g4 != v8) {
        // 0x80007b0
        v7 = v8;
        v8 = v7 + 1;
        v6 = v6 % 256 ^ (int32_t)*(char *)v7;
    }
    int32_t v9 = 0; // 0x80007c0
    if (v5 != v6) {
        // 0x80007e8
        return 0;
    }
    int32_t v10 = 0xffff; // 0x80007c0
    unsigned char v11 = *(char *)(v9 + (int32_t)&g3); // 0x80007cc
    v9 = (v9 + 1) % 0x10000;
    v10 &= (-1 << (int32_t)v11) - 1;
    while (v9 <= v1) {
        // 0x80007ca
        v11 = *(char *)(v9 + (int32_t)&g3);
        v9 = (v9 + 1) % 0x10000;
        v10 &= (-1 << (int32_t)v11) - 1;
    }
    // 0x80007dc
    *(int16_t *)&g3 = (int16_t)v10;
    // 0x80007e8
    return WriteOption(0x1fff0e8c, (int32_t)&g3, 1, v9);
}

// Address range: 0x80007fc - 0x8000852
int32_t APP_SystemClockConfig(int32_t a1, int32_t a2) {
    // 0x80007fc
    *(int32_t *)0x40021000 = *(int32_t *)0x40021000 | 256;
    *(int32_t *)0x40021004 = *(int32_t *)0x40021004 & -0x10000 | a1;
    while ((*(int32_t *)0x40021000 & 1024) == 0) {
        // continue -> 0x8000818
    }
    int32_t v1 = *(int32_t *)0x40021008; // 0x800081e
    *(int32_t *)0x40021008 = v1 & -3848;
    while ((v1 & 56) != 0) {
        // continue -> 0x8000832
    }
    // 0x8000838
    *(int32_t *)0x40022000 = *(int32_t *)0x40022000 & -2;
    *(int32_t *)0x40021008 = *(int32_t *)0x40021008 & -0x7001;
    return LL_SetSystemCoreClock(a2);
}

// Address range: 0x8000864 - 0x80008ac
// Demangled:     unsigned __int128 imaginary
int32_t Go(void) {
    // 0x8000864
    int32_t v1; // bp-20, 0x8000864
    uint32_t v2 = (GetAddressArea(&v1) + 255) % 256; // 0x8000872
    if (v2 != 1 && v2 != 0) {
        // 0x800087a
        return 0;
    }
    int32_t v3 = APP_SystemClockConfig(*(int32_t *)0x1fff0f04 % 0x2000 | 0x2000, 0x7a1200); // 0x8000892
    if ((*(int32_t *)v1 & 0x2ffe0000) == 0x20000000) {
        // 0x80008a8
        return __asm_cpsie(v3, 0x20000000, v1, 0x20000000);
    }
    // 0x800087a
    return 1;
}

// Address range: 0x80008c4 - 0x8000ad0
int32_t Bootloader_ProtocolDetection(void) {
    uint32_t v1 = USART_ReadByte(); // 0x80008c6
    if ((USART_ReadByte() ^ v1) % 256 != 255) {
        // 0x800093a
        return USART_SendByte(31);
    }
    // 0x80008da
    USART_SendByte(121);
    int32_t v2; // 0x80008c4
    int32_t v3; // 0x80008c4
    if (v1 == 115) {
        goto lab_0x800093c;
    } else {
        if (v1 < 115) {
            switch (v1) {
                case 99: {
                    goto lab_0x800093c;
                }
                case 68: {
                    goto lab_0x800093c;
                }
                case 49: {
                    goto lab_0x800093c;
                }
                default: {
                    // 0x80008f6
                    g11 = v1;
                    v3 = 31;
                    switch (v1) {
                        case 0: {
                            // 0x8000a3a
                            USART_SendByte(12);
                            USART_SendByte(16);
                            USART_SendByte(0);
                            if ((int32_t)&g9 == (int32_t)&g10) {
                                // 0x800093a
                                return USART_SendByte(121);
                            }
                            int32_t v4 = (int32_t)&g9;
                            int32_t v5 = v4 + 1; // 0x8000a50
                            USART_SendByte((int32_t)*(char *)v4);
                            v3 = 121;
                            while (v5 != (int32_t)&g10) {
                                // 0x8000a4e
                                v4 = v5;
                                v5 = v4 + 1;
                                USART_SendByte((int32_t)*(char *)v4);
                                v3 = 121;
                            }
                          lab_0x8000936:
                            // 0x800093a
                            return USART_SendByte(v3);
                        }
                        case 1: {
                            // 0x8000a60
                            USART_SendByte(16);
                            USART_SendByte(0);
                            USART_SendByte(0);
                            // 0x800093a
                            return USART_SendByte(121);
                        }
                        case 2: {
                            // 0x80009ee
                            USART_SendByte(1);
                            USART_SendByte(4);
                            USART_SendByte(64);
                            return USART_SendByte(121);
                        }
                        case 3: {
                            // 0x8000a76
                            USART_SendByte(1);
                            USART_SendByte(*(int32_t *)0x40015800 / 256 % 16);
                            USART_SendByte(*(int32_t *)0x40015800 % 256);
                            // 0x800093a
                            return USART_SendByte(121);
                        }
                        case 33: {
                            // 0x8000a9a
                            v2 = Go();
                            goto lab_0x8000930;
                        }
                        case 17: {
                            // 0x800093a
                            return ReadMemory();
                        }
                        default: {
                            return USART_SendByte(v3);
                        }
                    }
                }
            }
        } else {
            if ((v1 & 239) == 130) {
                goto lab_0x800093c;
            } else {
                goto lab_0x8000906;
            }
        }
    }
  lab_0x800093c:
    // 0x800093c
    if ((*(int32_t *)0x40022010 & 0x10000) != 0) {
        // 0x800093a
        return USART_SendByte(31);
    }
    // 0x8000944
    if (*(int32_t *)0x40022014 < 0) {
        // 0x800094a
        *(int32_t *)0x40022008 = -0x32107655;
        *(int32_t *)0x40022100 = *(int32_t *)0x1fff0f6c % 256;
        *(int32_t *)0x40022104 = *(int32_t *)0x1fff0f6c / 0x10000 % 512;
        *(int32_t *)0x40022110 = *(int32_t *)0x1fff0f6c / 256 % 256;
        *(int32_t *)0x40022108 = *(int32_t *)0x1fff0f70 % 256;
        *(int32_t *)0x4002210c = *(int32_t *)0x1fff0f70 / 0x10000 % 2048;
        *(int32_t *)0x40022114 = *(int32_t *)0x1fff0f74 % 0x20000;
        *(int32_t *)0x40022118 = *(int32_t *)0x1fff0f78 % 0x20000;
        *(int32_t *)0x4002211c = *(int32_t *)0x1fff0f7c % 0x10000;
        *(int32_t *)0x40022120 = *(int32_t *)0x1fff0f7c / 0x10000 % 0x4000;
    }
    int32_t v6; // 0x80008c4
    if (v1 == 49) {
        // 0x80008f6
        g11 = 49;
        v6 = WriteMemory();
        goto lab_0x8000924;
    } else {
        if (v1 == 115) {
            // 0x80009c6
            *(int16_t *)&g3 = 31;
            *(int16_t *)&g7 = -1;
            v6 = WriteOption(0x1fff0e84, (int32_t)&g3, 7, -1);
            goto lab_0x8000924;
        } else {
            if (v1 < 115) {
                // 0x80009e0
                v3 = 31;
                switch (v1) {
                    case 68: {
                        // 0x8000ab6
                        v6 = ExtendedErase();
                        goto lab_0x8000924;
                    }
                    case 99: {
                        // 0x80009e8
                        v6 = WriteProtect();
                        goto lab_0x8000924;
                    }
                    default: {
                        return USART_SendByte(v3);
                    }
                }
            } else {
                goto lab_0x8000906;
            }
        }
    }
  lab_0x8000924:
    // 0x8000924
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | -0x80000000;
    v2 = v6;
    goto lab_0x8000930;
  lab_0x8000906:
    // 0x8000906
    v3 = 31;
    switch (v1) {
        case 130: {
            // 0x8000aa6
            *(char *)&g3 = 85;
            v6 = WriteOption(0x1fff0e80, (int32_t)&g3, 0, 85);
            goto lab_0x8000924;
        }
        case 146: {
            // 0x8000912
            *(int16_t *)&g3 = -0x4f56;
            *(int16_t *)&g7 = 31;
            v6 = WriteOption(0x1fff0e80, (int32_t)&g3, 7, 31);
            goto lab_0x8000924;
        }
        default: {
            goto lab_0x8000936;
        }
    }
  lab_0x8000930:
    // 0x8000930
    if (v2 != 1) {
        // 0x800093a
        return USART_SendByte(31);
    }
    goto lab_0x8000a00;
  lab_0x8000a00:
    // 0x800093a
    return USART_SendByte(121);
}

// Address range: 0x8000b0c - 0x8000bd0
int32_t WriteFlash(int32_t a1, int32_t a2, int32_t a3) {
    uint32_t v1 = a3 + 1;
    if ((v1 | a1) % 128 != 0) {
        // 0x8000bc0
        return 0;
    }
    int32_t v2 = *(int32_t *)0x40022014 | 0x1000001; // 0x8000b3a
    *(int32_t *)0x40022014 = v2;
    int32_t v3 = 0; // 0x8000b42
    int32_t v4 = 0; // 0x8000b42
    int32_t v5 = v2; // 0x8000b42
    int32_t v6 = 1; // 0x8000b42
    if (v1 >= 128) {
        while (true) {
            int32_t v7 = 1; // 0x8000b54
            while (true) {
              lab_0x8000b5e:;
                int32_t v8 = v7;
                int32_t v9 = v3;
                *(int32_t *)(v9 + a1) = *(int32_t *)(v9 + a2);
                v3 = v9 + 4;
                switch ((int16_t)v8) {
                    case 31: {
                        // 0x8000b6c
                        *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x80000;
                        // 0x8000b5a
                        v7 = (v8 + 1) % 0x10000;
                        goto lab_0x8000b5e;
                    }
                    case 32: {
                        goto lab_0x8000b76;
                    }
                    default: {
                        // 0x8000b5a
                        v7 = (v8 + 1) % 0x10000;
                        goto lab_0x8000b5e;
                    }
                }
            }
          lab_0x8000b76:;
            uint32_t v10 = *(int32_t *)0x40022010; // 0x8000b76
            while ((v10 & 0x10000) != 0) {
                // continue -> 0x8000b76
            }
            // 0x8000b7c
            v6 = 0;
            if (v10 % 2 == 0) {
                // break -> 0x8000b98
                break;
            }
            // 0x8000b84
            *(int32_t *)0x40022010 = v10 | 1;
            v4 = (v4 + 1) % 0x10000;
            v6 = 1;
            if (v4 == v1 / 128) {
                // break -> 0x8000b98
                break;
            }
        }
        // 0x8000b98
        v5 = *(int32_t *)0x40022014;
    }
    // 0x8000b98
    *(int32_t *)0x40022014 = v5 & -0x1000002;
    int32_t v11 = a1; // 0x8000bac
    int32_t result = 0; // 0x8000bbc
    while (*(int32_t *)v11 == *(int32_t *)(a2 - a1 + v11)) {
        // 0x8000bac
        v11 += 4;
        result = v6;
        if ((v11 ^ v1 + a1) % 0x10000 == 0) {
            // break -> 0x8000bc0
            break;
        }
        result = 0;
    }
    // 0x8000bc0
    return result;
}

// Address range: 0x8000bdc - 0x8000ce2
int32_t WriteOption(int32_t a1, int32_t a2, uint32_t a3, int32_t a4) {
    // 0x8000bdc
    if ((*(int32_t *)0x40022014 & 0x40000000) != 0) {
        // 0x8000bf6
        *(int32_t *)0x4002200c = 0x4c5d6e7f;
    }
    uint32_t v1 = a3 % 0x10000; // 0x8000c06
    int32_t v2 = a1; // 0x8000c12
    int32_t v3 = a2; // 0x8000c12
    uint32_t v4 = 0; // 0x8000c12
    int32_t v5 = *(int32_t *)0x4002202c; // 0x8000c12
    int32_t v6 = *(int32_t *)0x40022024; // 0x8000c12
    int32_t v7 = *(int32_t *)0x40022020; // 0x8000c12
    int32_t v8; // 0x8000bdc
    int32_t v9; // 0x8000bdc
    int32_t v10; // 0x8000bdc
    int32_t v11; // 0x8000bdc
    int32_t v12; // 0x8000bdc
    int32_t v13; // 0x8000bdc
    int32_t v14; // 0x8000bdc
    int32_t v15; // 0x8000bdc
    int32_t v16; // 0x8000bdc
    while (true) {
      lab_0x8000c32_2:;
        int32_t v17 = v7;
        int32_t v18 = v6;
        int32_t v19 = v2; // 0x8000bdc
        int32_t v20 = v3; // 0x8000bdc
        int32_t v21 = v4; // 0x8000bdc
        int32_t v22 = v5; // 0x8000bdc
        while (true) {
          lab_0x8000c32:;
            int32_t v23 = v22;
            v10 = v21;
            v9 = v20;
            v8 = v19;
            v11 = v23;
            v13 = v18;
            v15 = v17;
            switch (v8) {
                case 0x1fff0e80: {
                    // 0x8000c36
                    v11 = v23;
                    v13 = v18;
                    v15 = v17 & -256 | (int32_t)*(char *)v9;
                    goto lab_0x8000c26;
                }
                case 0x1fff0e81: {
                    // 0x8000cb4
                    v11 = v23;
                    v13 = v18;
                    v15 = 256 * (int32_t)*(char *)v9 | v17 & -0xff01;
                    goto lab_0x8000c26;
                }
                case 0x1fff0e84: {
                    // 0x8000c1e
                    v11 = v23;
                    v13 = v18 & -256 | (int32_t)*(char *)v9;
                    v15 = v17;
                    goto lab_0x8000c26;
                }
                case 0x1fff0e85: {
                    // 0x8000ca8
                    v11 = v23;
                    v13 = 256 * (int32_t)*(char *)v9 | v18 & -0xff01;
                    v15 = v17;
                    goto lab_0x8000c26;
                }
                case 0x1fff0e8c: {
                    // 0x8000cc6
                    v11 = v23 & -256 | (int32_t)*(char *)v9;
                    v13 = v18;
                    v15 = v17;
                    goto lab_0x8000c26;
                }
                case 0x1fff0e8d: {
                    uint32_t v24 = (v10 + 1) % 0x10000; // 0x8000c4c
                    int32_t v25 = 256 * (int32_t)*(char *)v9 | v23 & -0xff01; // 0x8000c4e
                    v19 = 0x1fff0e8e;
                    v20 = v9 + 1;
                    v21 = v24;
                    v22 = v25;
                    v12 = v25;
                    v14 = v18;
                    v16 = v17;
                    if (v1 < v24) {
                        // break (via goto) -> 0x8000c58
                        goto lab_0x8000c58_2;
                    }
                    goto lab_0x8000c32;
                }
                default: {
                    goto lab_0x8000c26;
                }
            }
        }
        goto lab_0x8000c26;
    }
  lab_0x8000c58_2:
    // 0x8000c58
    *(int32_t *)0x40022020 = v16;
    *(int32_t *)0x40022024 = v14;
    *(int32_t *)0x4002202c = v12;
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x1020000;
    *(int32_t *)0x40022080 = 255;
    uint32_t v26 = *(int32_t *)0x40022010; // 0x8000c74
    while ((v26 & 0x10000) != 0) {
        // continue -> 0x8000c74
    }
    // 0x8000c7a
    *(int32_t *)0x40022010 = v26 | 1;
    uint32_t result = v26 % 2; // 0x8000c8a
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1020001;
    if (result != 0) {
        // 0x8000cd0
        USART_SendByte(121);
        *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x8000000;
    }
    // 0x8000c94
    return result;
  lab_0x8000c26:
    // 0x8000c26
    v7 = v15;
    v6 = v13;
    v5 = v11;
    v4 = (v10 + 1) % 0x10000;
    v2 = v8 + 1;
    v3 = v9 + 1;
    v12 = v5;
    v14 = v6;
    v16 = v7;
    if (v1 < v4) {
        // break -> 0x8000c58
        goto lab_0x8000c58_2;
    }
    goto lab_0x8000c32_2;
}

// Address range: 0x8000d14 - 0x8000dd2
int32_t PageErase(int32_t a1, uint32_t a2, uint32_t a3) {
    // 0x8000d14
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x1000002;
    uint32_t v1 = 1;
    int32_t v2; // 0x8000d14
    int32_t v3; // 0x8000d14
    int32_t v4; // 0x8000d14
    int32_t result; // 0x8000d14
    uint32_t v5; // 0x8000d9e
    uint16_t v6; // 0x8000d62
    uint32_t v7; // 0x8000d6e
    uint32_t v8; // 0x8000d88
    int32_t v9; // 0x8000d54
    uint32_t v10; // 0x8000d56
    int32_t v11; // 0x8000d98
    if (a3 != 0) {
        // 0x8000d4a
        v3 = 0;
        while (true) {
            // 0x8000d5c
            v4 = v3;
            WDG_Refresh();
            v6 = *(int16_t *)((2 * v1 + 510 & 510) + a1);
            v7 = 128 * ((int32_t)v6 * a3 + v4);
            if (v7 < 0xa000) {
                // 0x8000d76
                *(int32_t *)(v7 + 0x8000000) = -1;
                v8 = *(int32_t *)0x40022010;
                while ((v8 & 0x10000) != 0) {
                    // continue -> 0x8000d88
                }
                // 0x8000d8e
                result = 0;
                if (v8 % 2 == 0) {
                    // break (via goto) -> 0x8000db6
                    goto lab_0x8000db6;
                }
                // 0x8000d96
                v11 = v4 + 1;
                *(int32_t *)0x40022010 = v8 | 1;
                v5 = v11 % 256;
                v2 = v11;
                if (v5 <= a3 != v5 != a3) {
                    // break -> 0x8000da4
                    break;
                }
            } else {
                // 0x8000d54
                v9 = v4 + 1;
                v10 = v9 % 256;
                v2 = v9;
                if (v10 == a3 || v10 > a3) {
                    // break -> 0x8000da4
                    break;
                }
            }
            // 0x8000d5c
            v3 = v2;
        }
    }
    // 0x8000da4
    result = 1;
    while (v1 <= a2) {
        // 0x8000daa
        v1 = (v1 + 1) % 256;
        if (a3 != 0) {
            // 0x8000d4a
            v3 = 0;
            while (true) {
                // 0x8000d5c
                v4 = v3;
                WDG_Refresh();
                v6 = *(int16_t *)((2 * v1 + 510 & 510) + a1);
                v7 = 128 * ((int32_t)v6 * a3 + v4);
                if (v7 < 0xa000) {
                    // 0x8000d76
                    *(int32_t *)(v7 + 0x8000000) = -1;
                    v8 = *(int32_t *)0x40022010;
                    while ((v8 & 0x10000) != 0) {
                        // continue -> 0x8000d88
                    }
                    // 0x8000d8e
                    result = 0;
                    if (v8 % 2 == 0) {
                        // break (via goto) -> 0x8000db6
                        goto lab_0x8000db6;
                    }
                    // 0x8000d96
                    v11 = v4 + 1;
                    *(int32_t *)0x40022010 = v8 | 1;
                    v5 = v11 % 256;
                    v2 = v11;
                    if (v5 <= a3 != v5 != a3) {
                        // break -> 0x8000da4
                        break;
                    }
                } else {
                    // 0x8000d54
                    v9 = v4 + 1;
                    v10 = v9 % 256;
                    v2 = v9;
                    if (v10 == a3 || v10 > a3) {
                        // break -> 0x8000da4
                        break;
                    }
                }
                // 0x8000d5c
                v3 = v2;
            }
        }
        // 0x8000da4
        result = 1;
    }
  lab_0x8000db6:
    // 0x8000db6
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1000003;
    return result;
}

// Address range: 0x8000de4 - 0x8000e50
int32_t SectorErase(int32_t a1, uint32_t a2, int32_t a3, int32_t a4) {
    // 0x8000de4
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x1000800;
    uint32_t v1 = 0; // 0x8000e04
    WDG_Refresh();
    *(int32_t *)(0x1000 * (int32_t)*(int16_t *)(2 * v1 + a1) + 0x8000000) = -1;
    uint32_t v2 = *(int32_t *)0x40022010; // 0x8000e1c
    while ((v2 & 0x10000) != 0) {
        // continue -> 0x8000e1c
    }
    int32_t result = 0; // 0x8000e28
    while (v2 % 2 != 0) {
        // 0x8000e2a
        v1 = (v1 + 1) % 256;
        *(int32_t *)0x40022010 = v2 | 1;
        result = 1;
        if (v1 > a2) {
            // break -> 0x8000e3a
            break;
        }
        WDG_Refresh();
        *(int32_t *)(0x1000 * (int32_t)*(int16_t *)(2 * v1 + a1) + 0x8000000) = -1;
        v2 = *(int32_t *)0x40022010;
        while ((v2 & 0x10000) != 0) {
            // continue -> 0x8000e1c
        }
        // 0x8000e22
        result = 0;
    }
    // 0x8000e3a
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1000801;
    return result;
}

// Address range: 0x8000e5c - 0x8000e9c
int32_t MassErase(void) {
    // 0x8000e5c
    int32_t v1; // bp-18, 0x8000e5c
    int32_t v2 = &v1; // 0x8000e80
    int32_t v3 = &g8; // 0x8000e74
    uint32_t v4 = (v3 - 0x8000000) / 0x1000; // 0x8000e7c
    v1 = 0x10000 * v4 / 0x10000;
    int32_t v5; // 0x8000e5c
    int32_t result = SectorErase(v2, 0, v5, v4); // 0x8000e84
    while (result == 1) {
        // 0x8000e8c
        v3 += 0x1000;
        if (v3 <= 0x800a000 != v3 != 0x800a000) {
            // break -> 0x8000e98
            break;
        }
        v4 = (v3 - 0x8000000) / 0x1000;
        v1 = 0x10000 * v4 / 0x10000;
        result = SectorErase(v2, 0, v5, v4);
    }
    // 0x8000e98
    return result;
}

// Address range: 0x8000ea8 - 0x8000eb8
int32_t USART_SendByte(int32_t result) {
    // 0x8000ea8
    *(int32_t *)0x40013804 = result;
    while ((*(int32_t *)0x40013800 & 64) == 0) {
        // continue -> 0x8000eb0
    }
    // 0x8000eb6
    return result;
}

// Address range: 0x8000ebc - 0x8000eda
int32_t USART_ReadByte(void) {
    // 0x8000ebc
    if ((*(int32_t *)0x40013800 & 32) != 0) {
        // 0x8000ed2
        return *(int32_t *)0x40013804 % 256;
    }
    WDG_Refresh();
    while ((*(int32_t *)0x40013800 & 32) == 0) {
        // 0x8000ec8
        WDG_Refresh();
    }
    // 0x8000ed2
    return *(int32_t *)0x40013804 % 256;
}

// Address range: 0x8000ee0 - 0x8000f1c
int32_t WDG_Init(void) {
    int32_t v1 = *(int32_t *)0x40022020; // 0x8000ee2
    int32_t v2 = v1; // 0x8000ee6
    if ((v1 & 0x2000) == 0) {
        // 0x8000ee8
        *(int32_t *)0x40002c04 = *(int32_t *)0x40002c04 | 384;
        v2 = *(int32_t *)0x40022020;
    }
    // 0x8000ef4
    if ((v2 & 0x1000) == 0) {
        // 0x8000efc
        *(int32_t *)0x40003000 = 0x5555;
        *(int32_t *)0x40003004 = 7;
        *(int32_t *)0x40003008 = 4095;
    }
    // 0x8000f0a
    *(int32_t *)0x40002c00 = *(int32_t *)0x40002c00 | 127;
    *(int32_t *)0x40003000 = 0xaaaa;
    int32_t result; // 0x8000ee0
    return result;
}

// Address range: 0x8000f34 - 0x8000f46
int32_t WDG_Refresh(void) {
    // 0x8000f34
    *(int32_t *)0x40002c00 = *(int32_t *)0x40002c00 | 127;
    *(int32_t *)0x40003000 = 0xaaaa;
    int32_t result; // 0x8000f34
    return result;
}

// Address range: 0x8000f94 - 0x8000ff6
int32_t BSP_PB_Init(int32_t a1, int32_t a2) {
    if (a1 == 0) {
        // 0x8000f9c
        *(int32_t *)0x40021034 = *(int32_t *)0x40021034 | 1;
    }
    int32_t v1 = *(int32_t *)(4 * a1 + (int32_t)&g2); // 0x8000fb2
    int32_t * v2 = (int32_t *)v1; // 0x8000fb6
    int32_t v3 = *v2 & -0x3000001; // 0x8000fb8
    *v2 = v3;
    int32_t * v4 = (int32_t *)(v1 + 12); // 0x8000fbc
    *v4 = *v4 & -0x3000001;
    int32_t result = v3; // 0x8000fc4
    if (a2 == 1) {
        // 0x8000fca
        *(int32_t *)0x40021880 = *(int32_t *)0x40021880 | 0x1000;
        *(int32_t *)0x40021804 = *(int32_t *)0x40021804 | 0x1000;
        *(int32_t *)-0x1fff1bfc = *(int32_t *)-0x1fff1bfc % 0x1000000 | -0x40000000;
        *(int32_t *)-0x1fff1f00 = 128;
        result = -0x40000000;
    }
    // 0x8000fc6
    return result;
}

// Address range: 0x800100c - 0x800101a
int32_t BSP_PB_GetState(int32_t a1) {
    int32_t v1 = *(int32_t *)(4 * a1 + (int32_t)&g2); // 0x8001010
    return *(int32_t *)(v1 + 16) / 0x1000 % 2;
}

// Address range: 0x8001020 - 0x8001026
int32_t LL_SetSystemCoreClock(int32_t result) {
    // 0x8001020
    g1 = result;
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (10.3.1)
// Detected functions: 23

