//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(void);
int32_t function_1fff00c0(int32_t a1);
int32_t function_1fff00dc(void);
int32_t function_1fff00de(void);
int32_t function_1fff00e0(void);
int32_t function_1fff00e2(void);
int32_t function_1fff00e4(void);
int32_t function_1fff00e6(void);
int32_t function_1fff00f0(void);
int32_t function_1fff0114(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff029c(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff0480(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff0528(int32_t * a1);
int32_t function_1fff0628(void);
int32_t function_1fff0640(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff06a2(int32_t a1, int32_t a2, int32_t a3);
int32_t function_1fff06bc(void);
int32_t function_1fff0718(int32_t a1, int32_t a2, uint32_t a3);
int32_t function_1fff07b4(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff084c(int32_t result, int32_t a2);
int32_t function_1fff08a8(int32_t a1, int32_t a2, int32_t a3);
int32_t function_1fff08b8(void);
int32_t function_1fff08d4(int32_t a1);
int32_t function_1fff08e8(void);
int32_t function_1fff0910(void);
int32_t function_1fff0930(int32_t a1, int32_t a2, int32_t a3);
int32_t function_1fff0a14(int32_t a1, int32_t a2, int32_t result, int32_t a4);
int32_t function_1fff0aa4(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff0ba0(void);
int32_t function_1fff0bae(uint32_t a1);
int32_t function_1fff0bbc(void);
int32_t function_1fff0bc2(int32_t result, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff0c00(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_1fff0c70(void);
int32_t function_1fff8806(void);

// --------------------- Global Variables ---------------------

bool g1 = false; // 0x1fff0000
char * g2; // 0x1fff0470
char * g3; // 0x1fff0600
char * g4; // 0x1fff0840
int32_t g5 = 0x1fff0d0c; // 0x1fff0bcc
int32_t g6 = 0; // 0x1fff0bdc
char * g7; // 0x1fff0c68

// ------------------------ Functions -------------------------

// Address range: 0x1fff00c0 - 0x1fff00cc
int32_t function_1fff00c0(int32_t a1) {
    // 0x1fff00c0
    function_1fff00f0();
    return function_1fff0c70();
}

// Address range: 0x1fff00d4 - 0x1fff00dc
int32_t entry_point(void) {
    // 0x1fff00d4
    int32_t v1; // 0x1fff00d4
    function_1fff08a8(0x1fff08a9, v1, v1);
    return function_1fff00c0(0x1fff00c1);
}

// Address range: 0x1fff00dc - 0x1fff00de
int32_t function_1fff00dc(void) {
    // 0x1fff00dc
    return function_1fff00dc();
}

// Address range: 0x1fff00de - 0x1fff00e0
int32_t function_1fff00de(void) {
    // 0x1fff00de
    return function_1fff00de();
}

// Address range: 0x1fff00e0 - 0x1fff00e2
int32_t function_1fff00e0(void) {
    // 0x1fff00e0
    return function_1fff00e0();
}

// Address range: 0x1fff00e2 - 0x1fff00e4
int32_t function_1fff00e2(void) {
    // 0x1fff00e2
    return function_1fff00e2();
}

// Address range: 0x1fff00e4 - 0x1fff00e6
int32_t function_1fff00e4(void) {
    // 0x1fff00e4
    return function_1fff00e4();
}

// Address range: 0x1fff00e6 - 0x1fff00e8
int32_t function_1fff00e6(void) {
    // 0x1fff00e6
    return function_1fff00e6();
}

// Address range: 0x1fff00f0 - 0x1fff010c
int32_t function_1fff00f0(void) {
    // 0x1fff00f0
    if (&g5 >= &g6) {
        // 0x1fff0108
        int32_t result; // 0x1fff00f0
        return result;
    }
    int32_t v1 = &g5;
    int32_t v2 = v1 + 16; // 0x1fff0102
    while (v2 < (int32_t)&g6) {
        // 0x1fff00f8
        v1 = v2;
        v2 = v1 + 16;
    }
    // 0x1fff0108
    return *(int32_t *)v1;
}

// Address range: 0x1fff0114 - 0x1fff027c
int32_t function_1fff0114(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x1fff0114
    function_1fff08e8();
    *(int32_t *)0x40021034 = *(int32_t *)0x40021034 | 1;
    *(int32_t *)0x50000000 = *(int32_t *)0x50000000 & 0x3fcfff3f;
    int32_t v1 = *(int32_t *)0x1fff0d90; // 0x1fff0132
    if ((v1 & 8) == 0) {
        // 0x1fff0138
        *(int32_t *)0x5000000c = *(int32_t *)0x5000000c | 64;
    }
    if ((v1 & 1024) == 0) {
        // 0x1fff0144
        *(int32_t *)0x5000000c = *(int32_t *)0x5000000c | 0x100000;
    }
    if ((v1 & 0x8000) == 0) {
        // 0x1fff0152
        *(int32_t *)0x5000000c = *(int32_t *)0x5000000c | 0x40000000;
    }
    int32_t v2 = *(int32_t *)0x50000010;
    function_1fff0910();
    int32_t v3 = v2;
    int32_t v4 = v2 & 8; // 0x1fff017e
    int32_t v5 = v2 & 0x8000;
    int32_t v6 = v2 & 1024;
    int32_t v7 = v3 & 1024;
    int32_t v8 = -0x14140001; // 0x1fff019a
    int32_t v9 = 272; // 0x1fff019a
    while (v7 == 0 != v6 != 0) {
        int32_t v10 = v5;
        v5 = v3 & 0x8000;
        v8 = -0x54000001;
        v9 = 0x11000000;
        if (v5 == 0 == (v10 != 0)) {
            // break -> 0x1fff01be
            break;
        }
        int32_t v11 = v4;
        v3 = *(int32_t *)0x50000010;
        v4 = v3 & 8;
        function_1fff0910();
        if (v11 != 0 == v4 == 0) {
            // 0x1fff0222
            *(int32_t *)0x50000000 = -0x14000051;
            *(int32_t *)0x50000020 = *(int32_t *)0x50000020 | 0x1100;
            goto lab_0x1fff01c2;
        }
        v6 = v7;
        v7 = v3 & 1024;
        v8 = -0x14140001;
        v9 = 272;
    }
    // 0x1fff01be
    *(int32_t *)0x50000000 = v8;
    *(int32_t *)0x50000024 = *(int32_t *)0x50000024 | v9;
    goto lab_0x1fff01c2;
  lab_0x1fff01c2:
    // 0x1fff01c2
    *(int32_t *)0x40021040 = *(int32_t *)0x40021040 | 0x4000;
    *(int32_t *)0x4001380c = *(int32_t *)0x4001380c | 0x1400;
    *(int32_t *)0x40013808 = 208;
    *(int32_t *)0x40013814 = *(int32_t *)0x40013814 & -0x7001 | 0x1000;
    *(int32_t *)0x4001380c = *(int32_t *)0x4001380c | 0x2000;
    int32_t v12 = *(int32_t *)0x40013800; // 0x1fff01f6
    while ((v12 & 1024) == 0) {
        // continue -> 0x1fff01f6
    }
    if ((v12 & 2048) == 0) {
        uint32_t v13 = *(int32_t *)0x40013808; // 0x1fff0202
        if (v13 >= 24 && v13 >= 0x553a != v13 != 0x553a) {
            int32_t v14 = __asm_cpsid(); // 0x1fff0256
            int32_t * v15 = (int32_t *)v14; // 0x1fff0258
            *v15 = *v15 | 0x1000;
            int32_t * v16 = (int32_t *)(v14 + 20); // 0x1fff025e
            *v16 = *v16 & -0x1001;
            *v15 = *v15 & -97;
            int32_t * v17 = (int32_t *)(v14 + 12); // 0x1fff026c
            *v17 = *v17 | 12;
            return function_1fff08d4(121);
        }
    }
    // 0x1fff0210
    __asm_dsb();
    *(int32_t *)-0x1fff12f4 = 0x5fa0004;
    __asm_dsb();
    while (true) {
        // 0x1fff021e
        __asm_nop();
    }
}

// Address range: 0x1fff029c - 0x1fff0464
int32_t function_1fff029c(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = function_1fff08b8(); // 0x1fff02a0
    int32_t v2 = function_1fff08b8(); // 0x1fff02a6
    if ((v2 ^ v1) != 255) {
        // 0x1fff045e
        return function_1fff08d4(31);
    }
    int32_t v3; // 0x1fff029c
    int32_t v4; // 0x1fff029c
    if (v1 == 68) {
        goto lab_0x1fff02fe;
    } else {
        if (v1 > 68) {
            if (v1 == 146) {
                // 0x1fff0306
                v4 = function_1fff08d4(121);
                goto lab_0x1fff030c;
            } else {
                if (v1 > 146) {
                    if (v1 < 243) {
                        // 0x1fff0306
                        v4 = function_1fff08d4(121);
                        goto lab_0x1fff030c;
                    } else {
                        goto lab_0x1fff0320;
                    }
                } else {
                    // 0x1fff02e6
                    v4 = v2;
                    switch (v1) {
                        case 130: {
                            goto lab_0x1fff02fe;
                        }
                        case 115: {
                            goto lab_0x1fff02fe;
                        }
                        case 99: {
                            goto lab_0x1fff02fe;
                        }
                        default: {
                            goto lab_0x1fff030c;
                        }
                    }
                }
            }
        } else {
            if (v1 == 3) {
                // 0x1fff0306
                v4 = function_1fff08d4(121);
                goto lab_0x1fff030c;
            } else {
                if (v1 > 3) {
                    // 0x1fff02d2
                    v3 = v2;
                    switch (v1) {
                        case 49: {
                            goto lab_0x1fff02fe;
                        }
                        case 33: {
                            goto lab_0x1fff02fe;
                        }
                        case 17: {
                            goto lab_0x1fff02fe;
                        }
                        default: {
                            goto lab_0x1fff0312;
                        }
                    }
                } else {
                    // 0x1fff02c4
                    v3 = v2;
                    if (v1 < 3) {
                        // 0x1fff0306
                        v4 = function_1fff08d4(121);
                        goto lab_0x1fff030c;
                    } else {
                        goto lab_0x1fff0312;
                    }
                }
            }
        }
    }
  lab_0x1fff02fe:
    // 0x1fff02fe
    if ((*(int32_t *)0x40022020 & 255) != 170) {
        // 0x1fff045e
        return function_1fff08d4(31);
    }
    // 0x1fff0306
    v4 = function_1fff08d4(121);
    goto lab_0x1fff030c;
  lab_0x1fff030c:;
    bool v5 = true; // 0x1fff030e
    if (v1 == 115) {
        goto lab_0x1fff0328;
    } else {
        // 0x1fff0310
        v3 = v4;
        if (v1 > 115) {
            goto lab_0x1fff0320;
        } else {
            goto lab_0x1fff0312;
        }
    }
  lab_0x1fff0328:
    // 0x1fff0328
    if ((*(int32_t *)0x40022010 & 0x10000) != 0) {
        // 0x1fff045e
        return function_1fff08d4(31);
    }
    int32_t v6 = *(int32_t *)0x40022014; // 0x1fff032e
    bool v7 = v5; // 0x1fff0332
    int32_t v8 = v6; // 0x1fff0332
    if (v6 < 0) {
        // 0x1fff0334
        *(int32_t *)0x40022008 = -0x32107655;
        v7 = v5;
        v8 = -0x32107655;
    }
    goto lab_0x1fff033c;
  lab_0x1fff033c:;
    // 0x1fff033c
    int32_t v9; // 0x1fff029c
    int32_t v10; // 0x1fff029c
    int32_t v11; // 0x1fff029c
    int32_t v12; // 0x1fff029c
    int32_t v13; // 0x1fff029c
    int32_t v14; // 0x1fff029c
    if (v1 == 49) {
        // 0x1fff03fe
        v13 = function_1fff0a14(v8, 255, a3, a4);
        goto lab_0x1fff044c;
    } else {
        // 0x1fff0340
        if (v1 > 49) {
            int32_t v15 = (int32_t)g2;
            if (v7) {
                // 0x1fff043e
                *g2 = 31;
                *(char *)(v15 + 1) = 0;
                *(char *)(v15 + 4) = -1;
                *(char *)(v15 + 5) = -1;
                v13 = function_1fff0aa4(0x1fff0e84, v15, 7, 31);
                goto lab_0x1fff044c;
            } else {
                // 0x1fff036a
                v9 = v15;
                if (v1 > 115) {
                    goto lab_0x1fff0376;
                } else {
                    // 0x1fff036c
                    v12 = 0;
                    switch (v1) {
                        case 68: {
                            // 0x1fff0406
                            v13 = function_1fff0480(v8, v15, 0, 31);
                            goto lab_0x1fff044c;
                        }
                        case 99: {
                            // 0x1fff040c
                            v13 = function_1fff0c00(v8, v15, 0, 31);
                            goto lab_0x1fff044c;
                        }
                        default: {
                            goto lab_0x1fff0388;
                        }
                    }
                }
            }
        } else {
            if (v1 == 3) {
                // 0x1fff03da
                function_1fff08d4(1);
                function_1fff08d4(*(int32_t *)0x40015800 / 256 & 15);
                v10 = *(int32_t *)0x40015800 & 255;
                goto lab_0x1fff03d4;
            } else {
                if (v1 > 3) {
                    // 0x1fff0356
                    v14 = 0;
                    switch (v1) {
                        case 17: {
                            // 0x1fff03f2
                            return function_1fff07b4(v8, 255, a3, a4);
                        }
                        case 33: {
                            int32_t v16 = function_1fff0640(v8, 255, a3, a4); // 0x1fff03f8
                            v13 = v16;
                            v11 = v16;
                            if (v7) {
                                goto lab_0x1fff044c;
                            } else {
                                goto lab_0x1fff0456;
                            }
                        }
                        default: {
                            goto lab_0x1fff0382;
                        }
                    }
                } else {
                    // 0x1fff0348
                    v14 = 0;
                    switch (v1) {
                        case 0: {
                            // 0x1fff0396
                            function_1fff08d4(14);
                            function_1fff08d4(16);
                            int32_t v17 = 0; // 0x1fff03a2
                            function_1fff08d4((int32_t)*(char *)(v17 + 0x1fff0bbe));
                            v17 = v17 + 1 & 255;
                            v14 = 1;
                            while (v17 < 14) {
                                // 0x1fff03a4
                                function_1fff08d4((int32_t)*(char *)(v17 + 0x1fff0bbe));
                                v17 = v17 + 1 & 255;
                                v14 = 1;
                            }
                            goto lab_0x1fff0382;
                        }
                        case 1: {
                            // 0x1fff03b6
                            function_1fff08d4(16);
                            function_1fff08d4(0);
                            v10 = 0;
                            goto lab_0x1fff03d4;
                        }
                        case 2: {
                            // 0x1fff03c6
                            function_1fff08d4(1);
                            function_1fff08d4(4);
                            v10 = 64;
                            goto lab_0x1fff03d4;
                        }
                        default: {
                            goto lab_0x1fff0382;
                        }
                    }
                }
            }
        }
    }
  lab_0x1fff0320:
    // 0x1fff0320
    v5 = false;
    if ((v1 || 16) == 146) {
        goto lab_0x1fff0328;
    } else {
        // 0x1fff0340
        v9 = (int32_t)g2;
        goto lab_0x1fff0376;
    }
  lab_0x1fff0312:
    // 0x1fff0312
    v5 = false;
    v7 = false;
    v8 = v3;
    switch (v1) {
        case 99: {
            goto lab_0x1fff0328;
        }
        case 68: {
            goto lab_0x1fff0328;
        }
        case 49: {
            goto lab_0x1fff0328;
        }
        default: {
            goto lab_0x1fff033c;
        }
    }
  lab_0x1fff044c:
    // 0x1fff044c
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | -0x80000000;
    v11 = v13;
    goto lab_0x1fff0456;
  lab_0x1fff0376:;
    int32_t v18 = 0; // 0x1fff029c
    int32_t v19; // 0x1fff029c
    switch (v1) {
        case 130: {
            // 0x1fff0426
            *g2 = 85;
            v19 = 0;
            goto lab_0x1fff043e_2;
        }
        case 146: {
            // 0x1fff042e
            *g2 = -86;
            *(char *)(v9 + 1) = -80;
            *(char *)(v9 + 4) = 31;
            *(char *)(v9 + 5) = 0;
            v19 = 7;
            goto lab_0x1fff043e_2;
        }
        default: {
            goto lab_0x1fff0444;
        }
    }
  lab_0x1fff0456:
    // 0x1fff045e
    return function_1fff08d4(v11 == 0 ? 31 : 121);
  lab_0x1fff0444:
    // 0x1fff0444
    v13 = v18;
    v11 = v18;
    if ((v1 || 16) == 146) {
        goto lab_0x1fff044c;
    } else {
        goto lab_0x1fff0456;
    }
  lab_0x1fff03d4:
    // 0x1fff03d4
    function_1fff08d4(v10);
    v12 = 1;
    v13 = 1;
    if (v7) {
        goto lab_0x1fff044c;
    } else {
        goto lab_0x1fff0388;
    }
  lab_0x1fff043e_2:
    // 0x1fff043e
    v18 = function_1fff0aa4(0x1fff0e80, (int32_t)g2, v19, 31);
    goto lab_0x1fff0444;
  lab_0x1fff0388:
    // 0x1fff0388
    v13 = v12;
    v11 = v12;
    switch (v1) {
        case 99: {
            goto lab_0x1fff044c;
        }
        case 68: {
            goto lab_0x1fff044c;
        }
        case 49: {
            goto lab_0x1fff044c;
        }
        default: {
            goto lab_0x1fff0456;
        }
    }
  lab_0x1fff0382:
    // 0x1fff0382
    v13 = v14;
    if (v7) {
        goto lab_0x1fff044c;
    } else {
        // 0x1fff0386
        v12 = v14;
        v18 = v14;
        if (v1 > 115) {
            goto lab_0x1fff0444;
        } else {
            goto lab_0x1fff0388;
        }
    }
}

// Address range: 0x1fff0480 - 0x1fff0524
int32_t function_1fff0480(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = function_1fff08b8(); // 0x1fff0482
    int32_t v2 = function_1fff08b8(); // 0x1fff0488
    if (v1 == 255) {
        // 0x1fff04a2
        if (function_1fff08b8() == (v2 ^ 255)) {
            // 0x1fff04ac
            return function_1fff06bc();
        }
        // 0x1fff0506
        return 0;
    }
    uint32_t v3 = 2 * v2 + 2; // 0x1fff049c
    int32_t v4 = 0; // 0x1fff04c4
    if (v3 != 0) {
        *(char *)(v4 | 0x20000000) = (char)function_1fff08b8();
        v4 = v4 + 1 & 255;
        while (v3 >= v4 == (v3 != v4)) {
            // 0x1fff04b2
            *(char *)(v4 | 0x20000000) = (char)function_1fff08b8();
            v4 = v4 + 1 & 255;
        }
    }
    int32_t v5 = function_1fff0628(); // 0x1fff04cc
    if (function_1fff08b8() != v5) {
        // 0x1fff0506
        return 0;
    }
    uint32_t v6 = v2 + 1; // 0x1fff04de
    int32_t v7 = 0; // 0x1fff04f8
    if (v6 != 0) {
        int32_t v8 = 2 * v7; // 0x1fff04e2
        char * v9 = (char *)(v8 | 0x20000000); // 0x1fff04e4
        char * v10 = (char *)(v8 | 0x20000001); // 0x1fff04ea
        *v9 = *v10;
        *v10 = *v9;
        v7 = v7 + 1 & 255;
        while (v7 < v6) {
            // 0x1fff04e2
            v8 = 2 * v7;
            v9 = (char *)(v8 | 0x20000000);
            v10 = (char *)(v8 | 0x20000001);
            *v9 = *v10;
            *v10 = *v9;
            v7 = v7 + 1 & 255;
        }
    }
    // 0x1fff04fa
    switch (v1) {
        case 0: {
            // 0x1fff0510
            return function_1fff0718(0x20000000, v2, 8);
        }
        case 16: {
            // 0x1fff0510
            return function_1fff0718(0x20000000, v2, 1);
        }
        case 32: {
            // 0x1fff051a
            return function_1fff084c(0x20000000, v2);
        }
    }
    // 0x1fff0506
    return 0;
}

// Address range: 0x1fff0528 - 0x1fff0600
int32_t function_1fff0528(int32_t * a1) {
    int32_t v1 = function_1fff08b8(); // 0x1fff052c
    int32_t v2 = (int32_t)g3; // 0x1fff0530
    *g3 = (char)v1;
    int32_t v3 = function_1fff08b8(); // 0x1fff0534
    char * v4 = (char *)(v2 + 1); // 0x1fff0538
    *v4 = (char)v3;
    int32_t v5 = function_1fff08b8(); // 0x1fff053a
    char * v6 = (char *)(v2 + 2); // 0x1fff053e
    *v6 = (char)v5;
    int32_t v7 = function_1fff08b8(); // 0x1fff0540
    char * v8 = (char *)(v2 + 3); // 0x1fff0544
    *v8 = (char)v7;
    int32_t v9 = function_1fff08b8(); // 0x1fff0546
    if (v9 != function_1fff0628()) {
        // 0x1fff05da
        return 0;
    }
    // 0x1fff055a
    function_1fff08d4(121);
    unsigned char v10 = *g3; // 0x1fff0560
    unsigned char v11 = *v8; // 0x1fff0562
    unsigned char v12 = *v4; // 0x1fff0568
    unsigned char v13 = *v6; // 0x1fff056a
    int32_t v14 = 0x1000000 * (int32_t)v10 | (int32_t)v11 | 0x10000 * (int32_t)v12 | 256 * (int32_t)v13; // 0x1fff0572
    *a1 = v14;
    if (v14 == 0x1ffff7e0) {
        // 0x1fff05da
        return 3;
    }
    int32_t result; // 0x1fff0528
    if (v14 > 0x1ffff7e0) {
        // 0x1fff058e
        switch (v14) {
            case 0x1ffff7e8: {
                // 0x1fff0598
                *a1 = 0x1fff0e00;
                goto lab_0x1fff05a6;
            }
            case 0x1ffff800: {
                // 0x1fff05a4
                *a1 = 0x1fff0e80;
                goto lab_0x1fff05a6;
            }
            default: {
                goto lab_0x1fff05a6;
            }
        }
    } else {
        // 0x1fff0582
        result = 3;
        switch (v14) {
            case -2138: {
                // 0x1fff05a4
                *a1 = 0x1fff0bfc;
                goto lab_0x1fff05a6;
            }
            case -2100: {
                return result;
            }
            default: {
                goto lab_0x1fff05a6;
            }
        }
    }
  lab_0x1fff05a6:;
    unsigned char v15 = *(char *)0x1fff0ffc;
    result = 5;
    if ((0x2000 * (int32_t)v15 & 0xe000) < (int32_t)&g1) {
        // 0x1fff05da
        return 0;
    }
    // 0x1fff05da
    return result;
}

// Address range: 0x1fff0628 - 0x1fff063e
int32_t function_1fff0628(void) {
    // 0x1fff0628
    int32_t v1; // 0x1fff0628
    if (v1 == 0) {
        // 0x1fff063a
        int32_t result; // 0x1fff0628
        return result;
    }
    int32_t v2; // 0x1fff0628
    int32_t v3 = v2 + 0xffff & 0xffff; // 0x1fff0634
    int32_t v4; // 0x1fff0628
    int32_t v5; // 0x1fff0628
    int32_t result2 = v4 ^ (int32_t)*(char *)v5; // 0x1fff062c
    v5++;
    while (v3 != 0) {
        // 0x1fff062a
        v3 = v3 + 0xffff & 0xffff;
        result2 ^= (int32_t)*(char *)v5;
        v5++;
    }
    // 0x1fff063a
    return result2;
}

// Address range: 0x1fff0640 - 0x1fff06a0
int32_t function_1fff0640(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = a4; // bp-8, 0x1fff0640
    if (function_1fff0528(&v1) >= 3) {
        // 0x1fff0650
        return 0;
    }
    // 0x1fff0654
    *(int32_t *)0x40021034 = 0;
    *(int32_t *)0x40021040 = 0;
    *(int32_t *)0x4001380c = 0;
    *(int32_t *)0x40013808 = 0;
    *(int32_t *)0x50000000 = -0x14000001;
    *(int32_t *)0x50000020 = 0;
    *(int32_t *)0x50000024 = 0;
    int32_t v2 = *(int32_t *)0x40021004 & -0xe001 | 0x2000; // 0x1fff067e
    *(int32_t *)0x40021004 = v2;
    *(int32_t *)0x40021004 = v2 & -0xe000 | *(int32_t *)0x1fff0f04 & 0x1fff;
    while ((*(int32_t *)0x40021000 & 1024) == 0) {
        // continue -> 0x1fff0694
    }
    // 0x1fff069a
    __asm_cpsie();
    return -0x14000001;
}

// Address range: 0x1fff06a2 - 0x1fff06ac
int32_t function_1fff06a2(int32_t a1, int32_t a2, int32_t a3) {
    // 0x1fff06a2
    return 1;
}

// Address range: 0x1fff06bc - 0x1fff070a
int32_t function_1fff06bc(void) {
    // 0x1fff06bc
    if (*(int32_t *)0x4002202c != 0xffff) {
        // 0x1fff06d6
        return 0;
    }
    uint32_t v1 = *(int32_t *)0x40022024; // 0x1fff06c6
    uint32_t v2 = v1 & 31; // 0x1fff06ca
    uint32_t v3 = v1 / 256 & 31; // 0x1fff06d0
    if (v2 >= v3 != v2 != v3) {
        // 0x1fff06d6
        return 0;
    }
    // 0x1fff06da
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x1000004;
    *(int32_t *)0x8000000 = -1;
    int32_t v4 = *(int32_t *)0x40022010; // 0x1fff06ea
    while ((v4 & 0x10000) != 0) {
        // continue -> 0x1fff06ea
    }
    // 0x1fff06f0
    *(int32_t *)0x40022010 = v4 | 1;
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1000005;
    return v4 & 1;
}

// Address range: 0x1fff0718 - 0x1fff07a8
int32_t function_1fff0718(int32_t a1, int32_t a2, uint32_t a3) {
    int32_t v1 = *(int32_t *)0x40022014 | 0x1000002; // 0x1fff0726
    *(int32_t *)0x40022014 = v1;
    uint32_t v2 = a2 + 1; // 0x1fff072c
    if (v2 == 0) {
        // 0x1fff0798
        *(int32_t *)0x40022014 = v1 & -0x1000003;
        return 1;
    }
    int32_t v3 = 0;
    int32_t result; // 0x1fff0718
    int32_t v4; // 0x1fff0774
    int32_t v5; // 0x1fff078a
    uint32_t v6; // 0x1fff074a
    uint32_t v7; // 0x1fff075c
    if (a3 != 0) {
        // 0x1fff073c
        v5 = 0;
        function_1fff0910();
        v6 = 128 * ((int32_t)*(int16_t *)(2 * v3 + a1) * a3 + v5);
        v7 = 0x2000 * (int32_t)(*(char *)0x1fff0ffc & 7) + 0x2000;
        if (v7 >= v6 == (v7 != v6)) {
            // 0x1fff076c
            *(int32_t *)(v6 + 0x8000000) = -1;
            v4 = *(int32_t *)0x40022010;
            while ((v4 & 0x10000) != 0) {
                // continue -> 0x1fff0774
            }
            // 0x1fff077a
            result = 0;
            if ((v4 & 1) == 0) {
                // break (via goto) -> 0x1fff0794
                goto lab_0x1fff0794;
            }
            // 0x1fff0780
            *(int32_t *)0x40022010 = v4 | 1;
        }
        // 0x1fff0788
        v5 = v5 + 1 & 255;
        while (v5 < a3) {
            // 0x1fff073c
            function_1fff0910();
            v6 = 128 * ((int32_t)*(int16_t *)(2 * v3 + a1) * a3 + v5);
            v7 = 0x2000 * (int32_t)(*(char *)0x1fff0ffc & 7) + 0x2000;
            if (v7 >= v6 == (v7 != v6)) {
                // 0x1fff076c
                *(int32_t *)(v6 + 0x8000000) = -1;
                v4 = *(int32_t *)0x40022010;
                while ((v4 & 0x10000) != 0) {
                    // continue -> 0x1fff0774
                }
                // 0x1fff077a
                result = 0;
                if ((v4 & 1) == 0) {
                    // break (via goto) -> 0x1fff0794
                    goto lab_0x1fff0794;
                }
                // 0x1fff0780
                *(int32_t *)0x40022010 = v4 | 1;
            }
            // 0x1fff0788
            v5 = v5 + 1 & 255;
        }
    }
    int32_t v8 = v3 + 1 & 255; // 0x1fff0792
    result = 1;
    while (v8 < v2) {
        // 0x1fff0734
        v3 = v8;
        if (a3 != 0) {
            // 0x1fff073c
            v5 = 0;
            function_1fff0910();
            v6 = 128 * ((int32_t)*(int16_t *)(2 * v3 + a1) * a3 + v5);
            v7 = 0x2000 * (int32_t)(*(char *)0x1fff0ffc & 7) + 0x2000;
            if (v7 >= v6 == (v7 != v6)) {
                // 0x1fff076c
                *(int32_t *)(v6 + 0x8000000) = -1;
                v4 = *(int32_t *)0x40022010;
                while ((v4 & 0x10000) != 0) {
                    // continue -> 0x1fff0774
                }
                // 0x1fff077a
                result = 0;
                if ((v4 & 1) == 0) {
                    // break (via goto) -> 0x1fff0794
                    goto lab_0x1fff0794;
                }
                // 0x1fff0780
                *(int32_t *)0x40022010 = v4 | 1;
            }
            // 0x1fff0788
            v5 = v5 + 1 & 255;
            while (v5 < a3) {
                // 0x1fff073c
                function_1fff0910();
                v6 = 128 * ((int32_t)*(int16_t *)(2 * v3 + a1) * a3 + v5);
                v7 = 0x2000 * (int32_t)(*(char *)0x1fff0ffc & 7) + 0x2000;
                if (v7 >= v6 == (v7 != v6)) {
                    // 0x1fff076c
                    *(int32_t *)(v6 + 0x8000000) = -1;
                    v4 = *(int32_t *)0x40022010;
                    while ((v4 & 0x10000) != 0) {
                        // continue -> 0x1fff0774
                    }
                    // 0x1fff077a
                    result = 0;
                    if ((v4 & 1) == 0) {
                        // break (via goto) -> 0x1fff0794
                        goto lab_0x1fff0794;
                    }
                    // 0x1fff0780
                    *(int32_t *)0x40022010 = v4 | 1;
                }
                // 0x1fff0788
                v5 = v5 + 1 & 255;
            }
        }
        // 0x1fff0790
        v8 = v3 + 1 & 255;
        result = 1;
    }
  lab_0x1fff0794:
    // 0x1fff0798
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1000003;
    return result;
}

// Address range: 0x1fff07b4 - 0x1fff0840
int32_t function_1fff07b4(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = a4; // bp-16, 0x1fff07b4
    if (function_1fff0528(&v1) == 0) {
        // 0x1fff07d6
        return 0;
    }
    int32_t v2 = function_1fff08b8(); // 0x1fff07c0
    *g4 = (char)v2;
    if ((function_1fff08b8() ^ (int32_t)*g4) != 255) {
        // 0x1fff07d6
        return 0;
    }
    // 0x1fff07d8
    function_1fff08d4(121);
    int32_t v3 = 0; // 0x1fff0832
    switch (v1) {
        case -2080: {
        }
        case -2100: {
            int32_t v4 = (int32_t)g4; // 0x1fff07c4
            int32_t v5 = v4 + 1;
            *(char *)v5 = (8 * *(char *)0x1fff0ffc & 56) + 8;
            *(char *)(v4 + 2) = 0;
            *(char *)(v4 + 3) = (*(char *)0x1fff0ffc / 8 & 6) + 2;
            *(char *)(v4 + 4) = 0;
            int32_t v6 = 0; // 0x1fff081c
            function_1fff08d4((int32_t)*(char *)(v6 + v5));
            v6 = v6 + 1 & 0xffff;
            uint32_t v7 = (int32_t)*g4 + 1; // 0x1fff0820
            while (v7 >= v6 == (v7 != v6)) {
                // 0x1fff0812
                function_1fff08d4((int32_t)*(char *)(v6 + v5));
                v6 = v6 + 1 & 0xffff;
                v7 = (int32_t)*g4 + 1;
            }
            // 0x1fff07d6
            return 1;
        }
    }
    function_1fff08d4((int32_t)*(char *)(v3 + v1));
    v3 = v3 + 1 & 0xffff;
    uint32_t v8 = (int32_t)*g4 + 1; // 0x1fff0836
    while (v8 >= v3 == (v8 != v3)) {
        function_1fff08d4((int32_t)*(char *)(v3 + v1));
        v3 = v3 + 1 & 0xffff;
        v8 = (int32_t)*g4 + 1;
    }
    // 0x1fff07d6
    return 1;
}

// Address range: 0x1fff084c - 0x1fff089e
int32_t function_1fff084c(int32_t result, int32_t a2) {
    int32_t v1 = *(int32_t *)0x40022014 | 0x1000800; // 0x1fff0856
    *(int32_t *)0x40022014 = v1;
    uint32_t v2 = a2 + 1; // 0x1fff085e
    int32_t v3 = 0; // 0x1fff0890
    if (v2 == 0) {
        // 0x1fff0892
        *(int32_t *)0x40022014 = v1 & -0x1000801;
        return result;
    }
    function_1fff0910();
    *(int32_t *)(0x1000 * (int32_t)*(int16_t *)(2 * v3 + result) + 0x8000000) = -1;
    int32_t v4 = *(int32_t *)0x40022010; // 0x1fff0876
    while ((v4 & 0x10000) != 0) {
        // continue -> 0x1fff0876
    }
    int32_t result2 = 0; // 0x1fff0880
    while ((v4 & 1) != 0) {
        // 0x1fff0882
        *(int32_t *)0x40022010 = v4 | 1;
        v3 = v3 + 1 & 255;
        result2 = 1;
        if (v3 >= v2) {
            // break -> 0x1fff0892
            break;
        }
        function_1fff0910();
        *(int32_t *)(0x1000 * (int32_t)*(int16_t *)(2 * v3 + result) + 0x8000000) = -1;
        v4 = *(int32_t *)0x40022010;
        while ((v4 & 0x10000) != 0) {
            // continue -> 0x1fff0876
        }
        // 0x1fff087c
        result2 = 0;
    }
    // 0x1fff0892
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1000801;
    return result2;
}

// Address range: 0x1fff08a8 - 0x1fff08b8
int32_t function_1fff08a8(int32_t a1, int32_t a2, int32_t a3) {
    // 0x1fff08a8
    bool v1; // 0x1fff08a8
    if (v1) {
        *(int32_t *)(a3 - 8) = a1;
        int32_t v2; // 0x1fff08a8
        *(int32_t *)(a3 - 4) = (int32_t)&v2;
    }
    int32_t v3; // 0x1fff08a8
    return v1 ? v3 + (a1 >> 13) : a1;
}

// Address range: 0x1fff08b8 - 0x1fff08ce
int32_t function_1fff08b8(void) {
    // 0x1fff08b8
    if ((*(int32_t *)0x40013800 & 32) != 0) {
        // 0x1fff08c8
        return *(int32_t *)0x40013804 & 255;
    }
    function_1fff0910();
    while ((*(int32_t *)0x40013800 & 32) == 0) {
        // 0x1fff08be
        function_1fff0910();
    }
    // 0x1fff08c8
    return *(int32_t *)0x40013804 & 255;
}

// Address range: 0x1fff08d4 - 0x1fff08e2
int32_t function_1fff08d4(int32_t a1) {
    // 0x1fff08d4
    *(int32_t *)0x40013804 = a1;
    int32_t result = 0x2000000 * *(int32_t *)0x40013800; // 0x1fff08dc
    while (result >= 0) {
        // continue -> 0x1fff08da
    }
    // 0x1fff08e0
    return result;
}

// Address range: 0x1fff08e8 - 0x1fff0900
int32_t function_1fff08e8(void) {
    int32_t v1 = 0x80000 * *(int32_t *)0x40022020; // 0x1fff08ec
    int32_t result = v1; // 0x1fff08ee
    if (v1 >= 0) {
        // 0x1fff08f0
        *(int32_t *)0x40003000 = 0x5555;
        *(int32_t *)0x40003004 = 7;
        *(int32_t *)0x40003008 = 4095;
        result = 0x40003000;
    }
    // 0x1fff08fe
    return result;
}

// Address range: 0x1fff0910 - 0x1fff0922
int32_t function_1fff0910(void) {
    // 0x1fff0910
    *(int32_t *)0x40002c00 = *(int32_t *)0x40002c00 | 127;
    *(int32_t *)0x40003000 = 0xaaaa;
    return 0xaaaa;
}

// Address range: 0x1fff0930 - 0x1fff0a0c
int32_t function_1fff0930(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = a3 + 1; // 0x1fff0932
    uint32_t v2 = a1 & 127;
    int32_t v3 = a1; // 0x1fff0938
    if (v2 != 0) {
        if (v1 != 0) {
            int32_t v4 = v2 + a3 + a2; // 0x1fff0954
            int32_t v5 = 0; // 0x1fff095e
            int32_t v6 = 0;
            *(char *)(v4 + v6) = *(char *)(v6 + a2 + a3);
            v5 = v5 + 1 & 0xffff;
            while (v1 > v5) {
                // 0x1fff094a
                v6 = -v5;
                *(char *)(v4 + v6) = *(char *)(v6 + a2 + a3);
                v5 = v5 + 1 & 0xffff;
            }
        }
        // 0x1fff0968
        v3 = a1 & -128;
        int32_t v7 = 0;
        *(char *)(v7 + a2) = *(char *)(v7 + v3);
        int32_t v8 = v7 + 1 & 0xffff; // 0x1fff096e
        while (v2 >= v8 == (v2 != v8)) {
            // 0x1fff0968
            v7 = v8;
            *(char *)(v7 + a2) = *(char *)(v7 + v3);
            v8 = v7 + 1 & 0xffff;
        }
    }
    int32_t v9 = v1; // 0x1fff097a
    if (((v1 | a1) & 127) != 0) {
        int32_t v10 = v1 + v2; // 0x1fff0988
        uint32_t v11 = (a1 + 126 + v1 & -128 | 1) + -1 - v3; // 0x1fff098e
        if (v11 >= v10 == (v11 != v10)) {
            int32_t v12 = v10;
            *(char *)(v12 + a2) = *(char *)(v12 + v3);
            int32_t v13 = v12 + 1 & 0xffff; // 0x1fff0998
            while (v11 >= v13 == (v11 != v13)) {
                // 0x1fff0992
                v12 = v13;
                *(char *)(v12 + a2) = *(char *)(v12 + v3);
                v13 = v12 + 1 & 0xffff;
            }
        }
        // 0x1fff099e
        v9 = v11 & 0xffff;
    }
    int32_t v14 = *(int32_t *)0x40022014 | 0x1000001; // 0x1fff09a6
    *(int32_t *)0x40022014 = v14;
    uint32_t v15 = v9 / 128; // 0x1fff09ae
    int32_t v16 = 0; // 0x1fff09f4
    if (v9 < 128) {
        // 0x1fff09f6
        *(int32_t *)0x40022014 = v14 & -0x1000002;
        int32_t result; // 0x1fff0930
        return result;
    }
    int32_t v17 = 0; // 0x1fff09ce
    int32_t v18 = 0;
    *(int32_t *)(v18 + v3) = *(int32_t *)(v18 + a2);
    if (v17 == 30) {
        // 0x1fff09be
        *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x80000;
    }
    int32_t v19 = v18 + 4; // 0x1fff09b8
    v17 = v17 + 1 & 0xffff;
    while (v17 < 32) {
        // 0x1fff09b4
        v18 = v19;
        *(int32_t *)(v18 + v3) = *(int32_t *)(v18 + a2);
        if (v17 == 30) {
            // 0x1fff09be
            *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x80000;
        }
        // 0x1fff09cc
        v19 = v18 + 4;
        v17 = v17 + 1 & 0xffff;
    }
    int32_t v20 = *(int32_t *)0x40022010; // 0x1fff09d6
    while ((v20 & 0x10000) != 0) {
        // continue -> 0x1fff09d6
    }
    int32_t result2 = 0; // 0x1fff09e0
    while ((v20 & 1) != 0) {
        // 0x1fff09e2
        *(int32_t *)0x40022010 = v20 | 1;
        v16 = v16 + 1 & 0xffff;
        result2 = 1;
        if (v15 >= v16 != v15 != v16) {
            // break -> 0x1fff09f6
            break;
        }
        v17 = 0;
        v18 = v19;
        *(int32_t *)(v18 + v3) = *(int32_t *)(v18 + a2);
        if (v17 == 30) {
            // 0x1fff09be
            *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x80000;
        }
        // 0x1fff09cc
        v19 = v18 + 4;
        v17 = v17 + 1 & 0xffff;
        while (v17 < 32) {
            // 0x1fff09b4
            v18 = v19;
            *(int32_t *)(v18 + v3) = *(int32_t *)(v18 + a2);
            if (v17 == 30) {
                // 0x1fff09be
                *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x80000;
            }
            // 0x1fff09cc
            v19 = v18 + 4;
            v17 = v17 + 1 & 0xffff;
        }
        // 0x1fff09d6
        v20 = *(int32_t *)0x40022010;
        while ((v20 & 0x10000) != 0) {
            // continue -> 0x1fff09d6
        }
        // 0x1fff09dc
        result2 = 0;
    }
    // 0x1fff09f6
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1000002;
    return result2;
}

// Address range: 0x1fff0a14 - 0x1fff0aa0
int32_t function_1fff0a14(int32_t a1, int32_t a2, int32_t result, int32_t a4) {
    int32_t v1 = a2; // bp-32, 0x1fff0a14
    int32_t v2 = function_1fff0528(&v1); // 0x1fff0a18
    if (v2 >= 4) {
        // 0x1fff0a5a
        return 0;
    }
    int32_t v3 = function_1fff08b8(); // 0x1fff0a2a
    uint32_t v4 = v3 + 1; // 0x1fff0a32
    int32_t v5 = function_1fff08b8();
    int32_t v6 = v5; // 0x1fff0a44
    if (v4 != 0) {
        int32_t v7 = 0; // 0x1fff0a40
        *(char *)(v7 | 0x20000000) = (char)v5;
        v7 = v7 + 1 & 0xffff;
        int32_t v8 = function_1fff08b8();
        v6 = v8;
        while (v7 < v4) {
            // 0x1fff0a36
            *(char *)(v7 | 0x20000000) = (char)v8;
            v7 = v7 + 1 & 0xffff;
            v8 = function_1fff08b8();
            v6 = v8;
        }
    }
    // 0x1fff0a46
    if (v6 != function_1fff0628()) {
        // 0x1fff0a5a
        return 0;
    }
    // 0x1fff0a5e
    switch (v2) {
        case 1: {
            // 0x1fff0a5a
            return function_1fff0930(v1, 0x20000000, v3);
        }
        case 2: {
            // 0x1fff0a7a
            if (v4 == 0) {
                // 0x1fff0a5a
                return 1;
            }
            int32_t v9 = 0;
            *(char *)(v9 + v1) = *(char *)(v9 | 0x20000000);
            int32_t v10 = v9 + 1 & 0xffff; // 0x1fff0a88
            while (v10 < v4) {
                // 0x1fff0a82
                v9 = v10;
                *(char *)(v9 + v1) = *(char *)(v9 | 0x20000000);
                v10 = v9 + 1 & 0xffff;
            }
            // 0x1fff0a5a
            return 1;
        }
        case 3: {
            // 0x1fff0a5a
            return function_1fff0aa4(v1, 0x20000000, v3, a4);
        }
    }
    // 0x1fff0a5a
    return result;
}

// Address range: 0x1fff0aa4 - 0x1fff0b8e
int32_t function_1fff0aa4(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    int32_t v1 = *(int32_t *)0x40022020; // 0x1fff0aaa
    int32_t v2 = *(int32_t *)0x40022024; // 0x1fff0aac
    int32_t v3 = *(int32_t *)0x4002202c; // 0x1fff0aae
    if ((*(int32_t *)0x40022014 & 0x40000000) != 0) {
        // 0x1fff0ab6
        *(int32_t *)0x4002200c = 0x4c5d6e7f;
    }
    uint32_t v4 = a3 + 1; // 0x1fff0ac2
    int32_t v5 = v1; // 0x1fff0b40
    int32_t v6 = v2; // 0x1fff0b40
    int32_t v7 = v3; // 0x1fff0b40
    if (v4 != 0) {
        int32_t v8 = 0;
        int32_t v9 = v1; // 0x1fff0aa4
        int32_t v10 = v2; // 0x1fff0aa4
        int32_t v11 = v3; // 0x1fff0aa4
        switch (v8 + a1) {
            case 0x1fff0e80: {
                // 0x1fff0ad8
                v9 = v1 & -256 | (int32_t)*(char *)(v8 + a2);
                v10 = v2;
                v11 = v3;
                // break -> 0x1fff0b3a
                break;
            }
            case 0x1fff0e81: {
                // 0x1fff0ae0
                v9 = 256 * (int32_t)*(char *)(v8 + a2) | v1 & -0xff01;
                v10 = v2;
                v11 = v3;
                // break -> 0x1fff0b3a
                break;
            }
            case 0x1fff0e84: {
                // 0x1fff0af6
                v9 = v1;
                v10 = v2 & -256 | (int32_t)*(char *)(v8 + a2);
                v11 = v3;
                // break -> 0x1fff0b3a
                break;
            }
            case 0x1fff0e85: {
                // 0x1fff0b06
                v9 = v1;
                v10 = 256 * (int32_t)*(char *)(v8 + a2) | v2 & -0xff01;
                v11 = v3;
                // break -> 0x1fff0b3a
                break;
            }
            case 0x1fff0e8c: {
                // 0x1fff0b1c
                v9 = v1;
                v10 = v2;
                v11 = v3 & -256 | (int32_t)*(char *)(v8 + a2);
                // break -> 0x1fff0b3a
                break;
            }
            case 0x1fff0e8d: {
                // 0x1fff0b2c
                v9 = v1;
                v10 = v2;
                v11 = 256 * (int32_t)*(char *)(v8 + a2) | v3 & -0xff01;
                // break -> 0x1fff0b3a
                break;
            }
        }
        int32_t v12 = v11;
        int32_t v13 = v10;
        int32_t v14 = v9;
        int32_t v15 = v8 + 1 & 0xffff; // 0x1fff0b3c
        v5 = v14;
        v6 = v13;
        v7 = v12;
        while (v15 < v4) {
            // 0x1fff0ac6
            v8 = v15;
            int32_t v16 = v14;
            int32_t v17 = v13;
            int32_t v18 = v12;
            v9 = v16;
            v10 = v17;
            v11 = v18;
            switch (v8 + a1) {
                case 0x1fff0e80: {
                    // 0x1fff0ad8
                    v9 = v16 & -256 | (int32_t)*(char *)(v8 + a2);
                    v10 = v17;
                    v11 = v18;
                    // break -> 0x1fff0b3a
                    break;
                }
                case 0x1fff0e81: {
                    unsigned char v19 = *(char *)(v8 + a2); // 0x1fff0ae8
                    v9 = 256 * (int32_t)v19 | v16 & -0xff01;
                    v10 = v17;
                    v11 = v18;
                    // break -> 0x1fff0b3a
                    break;
                }
                case 0x1fff0e84: {
                    // 0x1fff0af6
                    v9 = v16;
                    v10 = v17 & -256 | (int32_t)*(char *)(v8 + a2);
                    v11 = v18;
                    // break -> 0x1fff0b3a
                    break;
                }
                case 0x1fff0e85: {
                    unsigned char v20 = *(char *)(v8 + a2); // 0x1fff0b0e
                    v9 = v16;
                    v10 = 256 * (int32_t)v20 | v17 & -0xff01;
                    v11 = v18;
                    // break -> 0x1fff0b3a
                    break;
                }
                case 0x1fff0e8c: {
                    // 0x1fff0b1c
                    v9 = v16;
                    v10 = v17;
                    v11 = v18 & -256 | (int32_t)*(char *)(v8 + a2);
                    // break -> 0x1fff0b3a
                    break;
                }
                case 0x1fff0e8d: {
                    // 0x1fff0b2c
                    v9 = v16;
                    v10 = v17;
                    v11 = 256 * (int32_t)*(char *)(v8 + a2) | v18 & -0xff01;
                    // break -> 0x1fff0b3a
                    break;
                }
            }
            // 0x1fff0b3a
            v12 = v11;
            v13 = v10;
            v14 = v9;
            v15 = v8 + 1 & 0xffff;
            v5 = v14;
            v6 = v13;
            v7 = v12;
        }
    }
    // 0x1fff0b42
    *(int32_t *)0x40022020 = v5;
    *(int32_t *)0x40022024 = v6;
    *(int32_t *)0x4002202c = v7;
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x1020000;
    *(int32_t *)0x40022080 = 255;
    int32_t v21 = *(int32_t *)0x40022010; // 0x1fff0b5c
    while ((v21 & 0x10000) != 0) {
        // continue -> 0x1fff0b5c
    }
    int32_t result = v21 & 1; // 0x1fff0b64
    *(int32_t *)0x40022010 = v21 | 1;
    *(int32_t *)0x40022014 = *(int32_t *)0x40022014 & -0x1020001;
    if (result != 0) {
        // 0x1fff0b7a
        function_1fff08d4(121);
        *(int32_t *)0x40022014 = *(int32_t *)0x40022014 | 0x8000000;
    }
    // 0x1fff0b8a
    return result;
}

// Address range: 0x1fff0ba0 - 0x1fff0bae
int32_t function_1fff0ba0(void) {
    // 0x1fff0ba0
    int32_t v1; // 0x1fff0ba0
    if (v1 == 0) {
        // 0x1fff0bac
        int32_t result; // 0x1fff0ba0
        return result;
    }
    int32_t v2; // 0x1fff0ba0
    int32_t result2 = v2 + 4; // 0x1fff0ba2
    int32_t v3; // 0x1fff0ba0
    int32_t v4 = v3 - 4; // 0x1fff0ba4
    int32_t v5; // 0x1fff0ba0
    *(int32_t *)v5 = *(int32_t *)v2;
    v5 += 4;
    v2 = result2;
    while (v4 != 0) {
        // 0x1fff0ba2
        result2 = v2 + 4;
        v4 -= 4;
        *(int32_t *)v5 = *(int32_t *)v2;
        v5 += 4;
        v2 = result2;
    }
    // 0x1fff0bac
    return result2;
}

// Address range: 0x1fff0bae - 0x1fff0bba
int32_t function_1fff0bae(uint32_t a1) {
    // 0x1fff0bae
    int32_t v1; // 0x1fff0bae
    uint32_t v2 = v1;
    bool v3 = false; // 0x1fff0bae
    bool v4; // 0x1fff0bae
    if (v4) {
        v3 = (a1 << 32 - v2 | a1 >> v2) < 0;
    }
    if (!v4 && true) {
        __asm_mrsgt(a1);
    }
    int32_t result = a1; // 0x1fff0bb6
    if (v3) {
        result = function_1fff8806();
    }
    // 0x1fff0bba
    return result;
}

// Address range: 0x1fff0bbc - 0x1fff0bbe
int32_t function_1fff0bbc(void) {
    // 0x1fff0bbc
    int32_t result; // 0x1fff0bbc
    return result;
}

// Address range: 0x1fff0bc2 - 0x1fff0bda
int32_t function_1fff0bc2(int32_t result, int32_t a2, int32_t a3, int32_t a4) {
    // 0x1fff0bc2
    return result;
}

// Address range: 0x1fff0c00 - 0x1fff0c62
int32_t function_1fff0c00(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    uint32_t v1 = function_1fff08b8() + 1; // 0x1fff0c0c
    int32_t v2 = function_1fff08b8();
    int32_t v3 = v2; // 0x1fff0c1e
    if (v1 != 0) {
        int32_t v4 = 0; // 0x1fff0c1a
        *(char *)(v4 + (int32_t)g7) = (char)v2;
        v4 = v4 + 1 & 0xffff;
        int32_t v5 = function_1fff08b8();
        v3 = v5;
        while (v4 < v1) {
            // 0x1fff0c10
            *(char *)(v4 + (int32_t)g7) = (char)v5;
            v4 = v4 + 1 & 0xffff;
            v5 = function_1fff08b8();
            v3 = v5;
        }
    }
    // 0x1fff0c20
    if (v3 != function_1fff0628()) {
        // 0x1fff0c34
        return 0;
    }
    int32_t v6 = (int32_t)g7;
    int32_t v7 = -1; // 0x1fff0c4e
    int32_t v8 = 0; // 0x1fff0c4e
    int32_t v9 = a4; // 0x1fff0c4e
    char v10 = -1; // 0x1fff0c4e
    char v11 = -1; // 0x1fff0c4e
    if (v1 != 0) {
        v9 = 1 << (int32_t)*(char *)(v8 + v6);
        v7 &= -1 - v9;
        v8 = v8 + 1 & 0xffff;
        while (v8 < v1) {
            // 0x1fff0c40
            v9 = 1 << (int32_t)*(char *)(v8 + v6);
            v7 &= -1 - v9;
            v8 = v8 + 1 & 0xffff;
        }
        // 0x1fff0c4c
        v10 = v7;
        v11 = v7 / 256;
    }
    // 0x1fff0c50
    *g7 = v10;
    *(char *)(v6 + 1) = v11;
    return function_1fff0aa4(0x1fff0e8c, v6, 1, v9);
}

// Address range: 0x1fff0c70 - 0x1fff0cf4
int32_t function_1fff0c70(void) {
    int32_t v1 = *(int32_t *)0x1fff0f10; // 0x1fff0c78
    *(int32_t *)0x40021004 = *(int32_t *)0x40021004 & -0x10000 | v1 & 0x1fff | 0x8000;
    while ((*(int32_t *)0x40021000 & 1024) == 0) {
        // continue -> 0x1fff0c8a
    }
    // 0x1fff0c90
    *(int32_t *)0x40022008 = -0x32107655;
    *(int32_t *)0x40022100 = *(int32_t *)0x1fff0f6c & 255;
    *(int32_t *)0x40022104 = *(int32_t *)0x1fff0f6c / 0x10000 & 511;
    *(int32_t *)0x40022110 = *(int32_t *)0x1fff0f6c / 256 & 255;
    *(int32_t *)0x40022108 = *(int32_t *)0x1fff0f70 & 255;
    *(int32_t *)0x4002210c = *(int32_t *)0x1fff0f70 / 0x10000 & 2047;
    *(int32_t *)0x40022114 = *(int32_t *)0x1fff0f74 & 0x1ffff;
    *(int32_t *)0x40022118 = *(int32_t *)0x1fff0f78 & 0x1ffff;
    int32_t v2 = *(int32_t *)0x1fff0f7c & 0xffff; // 0x1fff0cd6
    *(int32_t *)0x4002211c = v2;
    *(int32_t *)0x40022120 = *(int32_t *)0x1fff0f7c / 0x10000 & 0x3fff;
    int32_t v3 = *(int32_t *)0x40022014 | -0x80000000; // 0x1fff0ce6
    *(int32_t *)0x40022014 = v3;
    int32_t v4 = function_1fff0114(v3, -0x80000000, 0x40022000, v2); // 0x1fff0cea
    while (true) {
        // 0x1fff0cee
        v4 = function_1fff029c(v4, -0x80000000, 0x40022000, v2);
    }
}

// Address range: 0x1fff8806 - 0x1fff8807
int32_t function_1fff8806(void) {
    // 0x1fff8806
    int32_t result; // 0x1fff8806
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: msvc
// Detected functions: 35

